import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity, AppWindow, Bot, Boxes, CheckCircle2, ChevronDown, CircleHelp,
  Command, Compass, Database, FileCheck2, GitBranch, Layers3, LockKeyhole,
  Plus, Search, Settings2, ShieldCheck, Sparkles, Workflow, Wrench, X
} from 'lucide-react';
import './styles.css';

const modules = [
  { id: 'overview', label: 'Overview', icon: AppWindow, group: 'WORKSPACE' },
  { id: 'directory', label: 'AI Directory', icon: Compass, group: 'DISCOVER' },
  { id: 'skills', label: 'Skills Studio', icon: Layers3, group: 'DISCOVER' },
  { id: 'agents', label: 'Agent Builder', icon: Bot, group: 'BUILD' },
  { id: 'workflows', label: 'Orchestrator', icon: Workflow, group: 'BUILD' },
  { id: 'runtime', label: 'Secure Runtime', icon: ShieldCheck, group: 'OPERATE' },
  { id: 'evaluation', label: 'Evaluation & Audit', icon: FileCheck2, group: 'OPERATE' },
  { id: 'governance', label: 'Governance', icon: LockKeyhole, group: 'ADMIN' }
];

const initialCatalog = [
  { name: 'VoltAgent Agent Skills', type: 'Skill collection', category: 'Skills', source: 'VoltAgent/awesome-agent-skills', license: 'MIT · repo-level', url: 'https://github.com/VoltAgent/awesome-agent-skills', detail: 'Kumpulan referensi skill agent; lisensi setiap skill harus diverifikasi.' },
  { name: 'Awesome AI Agents', type: 'Agent directory', category: 'Agents', source: 'e2b-dev/awesome-ai-agents', license: 'CC BY-NC-SA 4.0', url: 'https://github.com/e2b-dev/awesome-ai-agents', detail: 'Referensi agent dan proyek. Materi berlisensi ini bukan default untuk distribusi komersial.' },
  { name: 'AI Collection', type: 'AI tools directory', category: 'Tools', source: 'ai-collection/ai-collection', license: 'MIT · repo-level', url: 'https://github.com/ai-collection/ai-collection', detail: 'Direktori tools AI; tinjau lisensi masing-masing produk dan aset.' },
  { name: 'Model Provider Adapter', type: 'Integration pattern', category: 'Infrastructure', source: 'Agent OS architecture', license: 'Internal design', url: 'https://github.com/Yudi8377/AGENT-OS', detail: 'Lapisan adapter provider dengan batas kredensial di server.' },
  { name: 'Sandbox Execution', type: 'Runtime capability', category: 'Infrastructure', source: 'Agent OS architecture', license: 'Needs integration', url: 'https://github.com/Yudi8377/AGENT-OS', detail: 'Eksekusi terisolasi belum aktif sampai runtime dikonfigurasi.' }
];

function App() {
  const [active, setActive] = useState('overview');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All');
  const [agents, setAgents] = useState([{ id: 1, name: 'Research Assistant', model: 'Belum tersambung', status: 'Draft', description: 'Menganalisis sumber dan merangkum temuan dengan sitasi.' }]);
  const [showCreate, setShowCreate] = useState(false);
  const [draft, setDraft] = useState({ name: '', purpose: '', instructions: '' });
  const [notice, setNotice] = useState('');
  const [tasks, setTasks] = useState([
    { name: 'Repository & license inventory', state: 'Complete' },
    { name: 'Provider credentials', state: 'Not connected' },
    { name: 'Sandbox runtime', state: 'Not connected' },
    { name: 'Persistent storage & RBAC', state: 'Planned' }
  ]);
  const current = modules.find(m => m.id === active) || modules[0];
  const catalog = useMemo(() => initialCatalog.filter(item => {
    const matchesQuery = [item.name, item.type, item.category, item.source].join(' ').toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (filter === 'All' || item.category === filter);
  }), [query, filter]);

  function createAgent(e) {
    e.preventDefault();
    if (!draft.name.trim() || !draft.purpose.trim()) return;
    setAgents(prev => [...prev, { id: Date.now(), name: draft.name.trim(), model: 'Belum tersambung', status: 'Draft', description: draft.purpose.trim(), instructions: draft.instructions }]);
    setDraft({ name: '', purpose: '', instructions: '' });
    setShowCreate(false);
    setActive('agents');
    setNotice('Draft agent disimpan di sesi browser ini. Belum tersimpan ke server dan belum dapat dieksekusi.');
  }

  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Command size={21}/></div><div><strong>AGENT<span>OS</span></strong><small>UNIFIED AGENT PLATFORM</small></div></div>
      <div className="workspace-switch"><div className="workspace-icon"><Boxes size={17}/></div><div><b>Personal Workspace</b><small>Starter environment</small></div><ChevronDown size={15}/></div>
      {['WORKSPACE', 'DISCOVER', 'BUILD', 'OPERATE', 'ADMIN'].map(group => <div className="nav-group" key={group}>
        <div className="nav-label">{group}</div>
        {modules.filter(m => m.group === group).map(m => <button key={m.id} className={'nav-item ' + (active === m.id ? 'selected' : '')} onClick={() => { setActive(m.id); setNotice(''); }}><m.icon size={17}/><span>{m.label}</span>{m.id === 'agents' && <em>{agents.length}</em>}</button>)}
      </div>)}
      <div className="sidebar-bottom"><div className="secure-note"><ShieldCheck size={16}/><div><b>Safety first</b><small>Runtime disabled until configured</small></div></div><button className="nav-item" onClick={() => setActive('governance')}><Settings2 size={17}/> Settings & access</button><div className="profile"><div className="avatar">Y</div><div><b>Yudi8377</b><small>Workspace owner</small></div><ChevronDown size={15}/></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="crumb"><span>Agent OS</span><span className="slash">/</span><b>{current.label}</b></div><div className="top-actions"><div className="environment"><i/> Local workspace</div><button className="icon-btn" title="Help" onClick={() => setNotice('Agent OS masih dalam tahap fondasi. Integrasi provider, runtime, dan penyimpanan perlu disiapkan sebelum produksi.')}><CircleHelp size={18}/></button><button className="avatar small-avatar" onClick={() => setActive('governance')}>Y</button></div></header>
      <div className="content">
        {notice && <div className="notice"><CheckCircle2 size={17}/><span>{notice}</span><button onClick={() => setNotice('')}><X size={15}/></button></div>}
        {active === 'overview' && <><div className="eyebrow"><Sparkles size={14}/> AGENT OPERATIONS CENTER</div><div className="page-heading"><div><h1>Build with agents.<br/><span>Operate with confidence.</span></h1><p>Temukan komponen AI, rancang agent, dan siapkan workflow dalam satu workspace.</p></div><button className="primary" onClick={() => setShowCreate(true)}><Plus size={17}/> Create agent</button></div>
          <div className="status-banner"><div className="status-icon"><LockKeyhole size={19}/></div><div><b>Runtime belum diaktifkan</b><p>Workspace siap untuk perancangan. Eksekusi agent dinonaktifkan sampai provider, sandbox, dan kebijakan akses dikonfigurasi.</p></div><button className="text-btn" onClick={() => setActive('runtime')}>Review setup <span>→</span></button></div>
          <div className="section-title"><div><h2>Workspace overview</h2><p>Ringkasan komponen yang sudah dirancang</p></div><span className="live-pill"><i/> DRAFT ENVIRONMENT</span></div>
          <div className="metric-grid"><Metric icon={Bot} label="Agents" value={agents.length} sub="Draft lokal" /><Metric icon={Layers3} label="Skill sources" value="3" sub="Sumber direferensikan" /><Metric icon={Workflow} label="Workflows" value="0" sub="Belum dieksekusi" /><Metric icon={Activity} label="Runtime status" value="Off" sub="Menunggu konfigurasi" /></div>
          <div className="two-col"><div className="panel"><div className="panel-head"><div><h3>Build your workspace</h3><p>Langkah awal implementasi</p></div><span className="muted-tag">FOUNDATION</span></div>{tasks.map((t,i)=><div className="task-row" key={t.name}><div className={'task-check '+(t.state==='Complete'?'done':'')}>{t.state==='Complete'?<CheckCircle2 size={17}/>:<span>{i+1}</span>}</div><div className="task-name">{t.name}</div><span className={'task-state '+(t.state==='Complete'?'good':'')}>{t.state}</span></div>)}</div><div className="panel gradient-panel"><div className="sparkle-bubble"><Sparkles size={20}/></div><div className="eyebrow">START HERE</div><h3>Turn an idea into an agent</h3><p>Buat definisi agent terlebih dahulu. Pilih provider dan tools nanti melalui konfigurasi server yang aman.</p><button className="secondary" onClick={() => setShowCreate(true)}>Open Agent Builder <span>→</span></button><div className="decor-grid"/></div></div>
          <div className="section-title lower"><div><h2>Reference catalog</h2><p>Tiga sumber yang menjadi fondasi Agent OS</p></div><button className="text-btn" onClick={() => setActive('directory')}>Browse directory →</button></div><div className="source-grid">{initialCatalog.slice(0,3).map(item=><SourceCard key={item.name} item={item}/>)}</div>
        </>}
        {active === 'directory' && <><PageHeader eyebrow="DISCOVER / CATALOG" title="AI Directory" subtitle="Cari tools, agent, dan koleksi skill dari sumber yang dapat ditelusuri." action={<span className="muted-tag">SOURCE-LINKED</span>}/><div className="search-row"><div className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools, agents, frameworks…"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Skills</option><option>Agents</option><option>Tools</option><option>Infrastructure</option></select></div><div className="result-count">{catalog.length} resources · sumber dan lisensi ditampilkan secara eksplisit</div><div className="catalog-grid">{catalog.map(item=><SourceCard key={item.name} item={item}/>)}</div></>}
        {active === 'skills' && <><PageHeader eyebrow="DISCOVER / EXTENSIONS" title="Skills Studio" subtitle="Kelola metadata dan proses review skill sebelum pemasangan." action={<button className="primary" onClick={()=>setNotice('Import skill memerlukan parser, pemeriksaan lisensi, validasi manifest, dan sandbox. Belum diaktifkan.') }><Plus size={16}/> Import skill</button>}/><div className="status-banner compact"><ShieldCheck size={19}/><div><b>Review before install</b><p>Skill pihak ketiga tidak dijalankan otomatis. Verifikasi sumber, lisensi, akses tool, dan instruksi sebelum menyetujuinya.</p></div></div><div className="catalog-grid">{initialCatalog.filter(x=>x.category==='Skills'||x.category==='Infrastructure').map(item=><SourceCard key={item.name} item={item}/>)}</div><div className="panel"><h3>Skill approval checklist</h3><div className="checklist"><span><CheckCircle2/> Provenance & source URL</span><span><CheckCircle2/> License and redistribution terms</span><span><CheckCircle2/> Requested tools and permissions</span><span><CheckCircle2/> Static security review</span><span><LockKeyhole/> Sandboxed test before activation</span></div></div></>}
        {active === 'agents' && <><PageHeader eyebrow="BUILD / CONFIGURATION" title="Agent Builder" subtitle="Definisikan tujuan, instruksi, dan konfigurasi agent sebelum menghubungkan runtime." action={<button className="primary" onClick={()=>setShowCreate(true)}><Plus size={17}/> New agent</button>}/><div className="agent-list">{agents.map(a=><div className="agent-card" key={a.id}><div className="agent-icon"><Bot size={22}/></div><div className="agent-info"><div className="agent-title"><h3>{a.name}</h3><span className="draft-pill">{a.status}</span></div><p>{a.description}</p><div className="agent-meta"><span><Sparkles size={14}/>{a.model}</span><span><Wrench size={14}/> Tools: none</span></div></div><button className="secondary small-btn" onClick={()=>setNotice('Agent '+a.name+' masih berupa definisi lokal. Eksekusi tersedia setelah provider dan runtime aman tersambung.')}>Configure <span>→</span></button></div>)}</div><div className="panel"><h3>Execution contract</h3><p className="muted-copy">Agent tidak dapat berjalan hanya karena definisinya tersimpan. Implementasi berikutnya menghubungkan model provider, tool registry, secret storage, batas biaya, dan runtime terisolasi.</p></div></>}
        {active === 'workflows' && <><PageHeader eyebrow="BUILD / ORCHESTRATION" title="Orchestrator" subtitle="Rancang alur multi-step dan multi-agent dengan persetujuan di titik kritis." action={<button className="primary" onClick={()=>setNotice('Workflow editor akan dibuat dengan state persistence, node validation, retry policy, dan approval gates. Runner belum aktif.') }><Plus size={17}/> New workflow</button>}/><div className="workflow-canvas"><div className="canvas-top"><span><GitBranch size={16}/> Untitled workflow</span><span className="draft-pill">Not deployed</span></div><div className="flow-nodes"><FlowNode icon={Sparkles} title="Input" subtitle="User request" /><div className="connector"/><FlowNode icon={Bot} title="Agent step" subtitle="Model + tools" /><div className="connector"/><FlowNode icon={FileCheck2} title="Review gate" subtitle="Human approval" /><div className="connector"/><FlowNode icon={CheckCircle2} title="Output" subtitle="Validated result" /></div><p className="canvas-foot">Conceptual workflow preview · not executable</p></div><div className="metric-grid"><Metric icon={Workflow} label="Workflow drafts" value="0" sub="Belum disimpan" /><Metric icon={GitBranch} label="Approval gates" value="Design" sub="Human-in-the-loop" /><Metric icon={Activity} label="Runs" value="0" sub="Runner belum terhubung" /></div></>}
        {active === 'runtime' && <><PageHeader eyebrow="OPERATE / SECURITY" title="Secure Runtime" subtitle="Lapisan eksekusi agent dengan isolasi, izin minimum, dan batas resource." action={<span className="off-pill"><i/> DISABLED</span>}/><div className="runtime-hero"><div className="runtime-lock"><ShieldCheck size={30}/></div><div><h2>Execution is locked by default</h2><p>Belum ada kode agent atau skill pihak ketiga yang dijalankan. Ini disengaja sampai konfigurasi keamanan diverifikasi.</p></div></div><div className="security-grid">{[['Provider secrets','Simpan di server secret manager; jangan expose ke browser.'],['Sandbox isolation','Jalankan tool dalam lingkungan terisolasi dengan batas waktu dan resource.'],['Least privilege','Berikan hanya tool dan scope yang dibutuhkan agent.'],['Network controls','Batasi egress, host tujuan, ukuran payload, dan waktu eksekusi.'],['Budget limits','Tentukan limit token, biaya, concurrency, dan durasi per run.'],['Approval gates','Minta persetujuan sebelum aksi eksternal atau perubahan data.']].map(([t,d])=><div className="security-card" key={t}><LockKeyhole size={18}/><b>{t}</b><p>{d}</p><span className="task-state">Needs implementation</span></div>)}</div></>}
        {active === 'evaluation' && <><PageHeader eyebrow="OPERATE / QUALITY" title="Evaluation & Audit" subtitle="Rencanakan pengukuran kualitas, biaya, keandalan, dan jejak tindakan agent." action={<button className="secondary" onClick={()=>setNotice('Evaluasi belum dijalankan: belum ada runtime atau hasil run untuk dinilai.')}>Run evaluation</button>}/><div className="metric-grid"><Metric icon={CheckCircle2} label="Test cases" value="0" sub="Belum dibuat" /><Metric icon={Activity} label="Success rate" value="—" sub="Belum ada eksekusi" /><Metric icon={Database} label="Audit events" value="0" sub="Storage belum terhubung" /><Metric icon={Wrench} label="Tool errors" value="—" sub="Runtime belum aktif" /></div><div className="panel"><h3>Evaluation plan</h3>{['Correctness and groundedness','Tool-call schema and permission checks','Prompt-injection and untrusted-input tests','Latency, token usage, and budget limits','Regression tests for each agent revision'].map((x,i)=><div className="task-row" key={x}><div className="task-check"><span>{i+1}</span></div><div className="task-name">{x}</div><span className="task-state">Planned</span></div>)}</div><div className="panel"><h3>Audit event schema (planned)</h3><p className="muted-copy">actor · workspace · agent_version · action · tool · permission_decision · timestamp · result · latency · usage · correlation_id</p></div></>}
        {active === 'governance' && <><PageHeader eyebrow="ADMIN / TRUST" title="Governance & access" subtitle="Kontrol workspace, izin berbasis peran, provenance, dan pengelolaan secret." action={<span className="muted-tag">OWNER VIEW</span>}/><div className="security-grid">{[['Workspace isolation','Data dan konfigurasi tiap workspace harus dipisahkan.'],['Role-based access','Owner, Admin, Builder, Operator, Reviewer, Viewer.'],['Secret management','Kredensial provider hanya tersedia pada server runtime.'],['Audit trail','Catat perubahan konfigurasi dan keputusan akses.'],['License registry','Simpan sumber, versi, lisensi, dan pemeriksaan terakhir.'],['Data retention','Tetapkan masa simpan log, ekspor, dan penghapusan.']].map(([t,d])=><div className="security-card" key={t}><ShieldCheck size={18}/><b>{t}</b><p>{d}</p><span className="task-state">Design defined</span></div>)}</div><div className="panel"><h3>Connected identity</h3><div className="identity-row"><div className="avatar">Y</div><div><b>Yudi8377</b><p>GitHub repository owner · Agent OS workspace preview</p></div><span className="good-pill">Verified</span></div><p className="muted-copy">Identitas tampilan ini belum menjadi sistem autentikasi aplikasi. Implementasi produksi memerlukan autentikasi server, sesi aman, dan RBAC yang diverifikasi di backend.</p></div></>}
      </div>
    </main>
    {showCreate && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowCreate(false)}}><form className="modal" onSubmit={createAgent}><div className="modal-head"><div><span className="eyebrow">AGENT BUILDER</span><h2>Create agent draft</h2></div><button type="button" className="icon-btn" onClick={()=>setShowCreate(false)}><X/></button></div><label>Agent name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="e.g. Research Assistant"/></label><label>Purpose<input required value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value})} placeholder="What should this agent help with?"/></label><label>Instructions<textarea value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})} placeholder="Define behavior, boundaries, and output format…" rows={4}/></label><div className="modal-warning"><LockKeyhole size={16}/> This creates a local draft only. No model calls or external actions will run.</div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="primary" type="submit"><Plus size={16}/> Save draft</button></div></form></div>}
  </div>;
}

function Metric({icon:Icon,label,value,sub}) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{sub}</small></div>; }
function PageHeader({eyebrow,title,subtitle,action}) { return <div className="subpage-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
function SourceCard({item}) { return <article className="source-card"><div className="source-icon"><AppWindow size={19}/></div><div className="source-type">{item.type}</div><h3>{item.name}</h3><p>{item.detail}</p><div className="source-meta"><span>{item.license}</span></div><a href={item.url} target="_blank" rel="noreferrer">View source <span>↗</span></a></article>; }
function FlowNode({icon:Icon,title,subtitle}) { return <div className="flow-node"><div><Icon size={19}/></div><b>{title}</b><small>{subtitle}</small></div>; }

createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
